[general]
live_config_reload = true
[window]
decorations = "None"
opacity = 0.8
blur = true
option_as_alt = "Both"
[font]
normal = { family = "RecMonoSmCasual Nerd Font Mono" }
size = 15
[keyboard]
bindings = [
  { key = "1", mods = "Command", action = "ToggleViMode" }
]
