[settings]
animate = false
auto_focus_blacklist = ["com.apple.SecurityAgent"]
hot_reload = true

[settings.layout]
mode = "traditional"

[settings.layout.stack]
stack_offset = 0.0
default_orientation = "perpendicular"

[settings.layout.gaps.outer]
top = 5
left = 5
bottom = 5
right = 5

[settings.layout.gaps.inner]
horizontal = 5
vertical = 5

[settings.ui.menu_bar]
enabled = true
show_empty = false
mode = "all"
active_label = "index"
display_style = "label"

[settings.ui.stack_line]
enabled = false

[settings.ui.mission_control]
enabled = false

[settings.gestures]
enabled = false

[settings.window_snapping]
drag_swap_fraction = 0.3

[virtual_workspaces]
enabled = true
default_workspace = 0
default_workspace_count = 9
auto_assign_windows = true
preserve_focus_per_workspace = true
workspace_auto_back_and_forth = false
reapply_app_rules_on_title_change = true
app_rules = [
  { app_id = "com.apple.systempreferences",     floating = true },
  { app_id = "org.hammerspoon.Hammerspoon",     floating = true },
  { app_id = "com.aone.keka",                   floating = true },
  { app_id = "com.apple.finder",                floating = true },
  { app_id = "com.colliderli.iina",             floating = true },
  { app_id = "com.baidu.netdisk",               floating = true },
  { app_id = "com.metacubex.ClashX.meta",       floating = true },
  { app_id = "com.rlxone.equinox",              floating = true },
  { app_id = "com.apple.FinalCut",              floating = true },
  { app_id = "org.kde.kid3",                    floating = true },
  { app_id = "com.apple.logic10",               floating = true },
  { app_id = "com.sarensx.MacPacker",           floating = true },
  { app_id = "com.pixelmatorteam.pixelmator.x", floating = true },
  { app_id = "com.dreamtonics.svstudio2.pro",   floating = true },
  { app_id = "com.tencent.meeting",             floating = true },
  { app_id = "com.apple.ScreenContinuity",      floating = true },
  { app_id = "com.apple.Compressor",            floating = true },
  { app_id = "com.apple.motionapp",             floating = true },
]

[modifier_combinations]
comb1 = "Ctrl + Meta"
[keys]
"comb1 + Z" = "toggle_space_activated"
"comb1 + H" = { move_focus = "left" }
"comb1 + J" = { move_focus = "down" }
"comb1 + K" = { move_focus = "up" }
"comb1 + L" = { move_focus = "right" }

"comb1 + N" = { move_node = "left" }
"comb1 + M" = { move_node = "down" }
"comb1 + ," = { move_node = "up" }
"comb1 + ." = { move_node = "right" }

"Ctrl + 1" = { switch_to_workspace = 0 }
"Ctrl + 2" = { switch_to_workspace = 1 }
"Ctrl + 3" = { switch_to_workspace = 2 }
"Ctrl + 4" = { switch_to_workspace = 3 }
"Ctrl + 5" = { switch_to_workspace = 4 }
"Ctrl + 6" = { switch_to_workspace = 5 }
"Ctrl + 7" = { switch_to_workspace = 6 }
"Ctrl + 8" = { switch_to_workspace = 7 }
"Ctrl + 9" = { switch_to_workspace = 8 }

"comb1 + 1" = { move_window_to_workspace = 0 }
"comb1 + 2" = { move_window_to_workspace = 1 }
"comb1 + 3" = { move_window_to_workspace = 2 }
"comb1 + 4" = { move_window_to_workspace = 3 }
"comb1 + 5" = { move_window_to_workspace = 4 }
"comb1 + 6" = { move_window_to_workspace = 5 }
"comb1 + 7" = { move_window_to_workspace = 6 }
"comb1 + 8" = { move_window_to_workspace = 7 }
"comb1 + 9" = { move_window_to_workspace = 8 }
"comb1 + Left" = { join_window = "left" }
"comb1 + Right" = { join_window = "right" }
"comb1 + Up" = { join_window = "up" }
"comb1 + Down" = { join_window = "down" }
"comb1 + T" = "toggle_window_floating"
"comb1 + O" = "toggle_fullscreen_within_gaps"
"comb1 + Equal" = "resize_window_grow"
"comb1 + Minus" = "resize_window_shrink"
